# action.yml
name: 'Sceptre Config Linter'
description: 'Validate params in scepte config files'
inputs:
  project-home:  # id of input
    description: 'Sceptre project home'
    required: true
  cfn-lint-options:
    description: 'cfn-lint options to pass: eg. "-i W2001,W3001"'
    required: false
  skip-patterns: 
    description: 'comma-delimited file spec tappters'
    required: false
  linter-ignore-codes: 
    description: 'comma-delimited codes'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "${{ inputs.cfn-lint-options }} -s ${{ inputs.skip-patterns }} -ti ${{ inputs.linter-ignore-codes }} ${{ inputs.project-home }}"

