on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test Action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test acion step
        uses: ./ # Uses an action in the root directory
        with:
          project-home: './'

